/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE examBaseService PLEASE EDIT ../exam.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exam } from '../../domain/schoolprpject_db/exam';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../exam.service.ts
 */

/*
 * SCHEMA DB exam
 *
	{
		place: {
			type: 'String'
		},
		score: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		course: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		exam: {
			type: Schema.ObjectId,
			ref : "subject"
		},
		student: {
			type: Schema.ObjectId,
			ref : "exam"
		},
	}
 *
 */
@Injectable()
export class ExamBaseService {

    contextUrl: string = environment.endpoint + '/exam';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * examService.findBycourse
    *   @description CRUD ACTION findBycourse
    *   @param Objectid key Id of model to search for
    *
    */
    findByCourse(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBycourse/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examService.findBystudent
    *   @description CRUD ACTION findBystudent
    *   @param Objectid key Id of model to search for
    *
    */
    findByStudent(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBystudent/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl)
            .pipe(map(data => data));
    }


    // Custom APIs

}
