/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE student-nameBaseService PLEASE EDIT ../student-name.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { StudentName } from '../../domain/schoolprpject_db/student-name';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../studentName.service.ts
 */

/*
 * SCHEMA DB studentName
 *
	{
		age: {
			type: 'Number'
		},
		dateofbirth: {
			type: 'Date'
		},
		name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		student: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		subject: {
			type: Schema.ObjectId,
			ref : "subject"
		},
	}
 *
 */
@Injectable()
export class StudentNameBaseService {

    contextUrl: string = environment.endpoint + '/studentname';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * studentNameService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: StudentName): Observable<StudentName> {
        return this.http
            .post<StudentName>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * studentNameService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * studentNameService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<StudentName> {
        return this.http
            .get<StudentName>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * studentNameService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<StudentName[]> {
        return this.http
            .get<StudentName[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * studentNameService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: StudentName): Observable<StudentName> {
        return this.http
            .post<StudentName>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
